default:
  type: "mysql"
  host: "localhost"
  port: 3306
  username: "root"
  password: "password"
  database: "UBuyDB"

docstore:
  type: "mongodb"
  url: ""
  port: ""
  username: ""
  password: ""
  database: ""
